version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myljail
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myljail
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8100:8080"

  discordbot:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db